### ISSUE TITLE
Preprocessing corpora generation

### ISSUE THREAD

**Issue by MorenoLaQuatra** [julmaxi/Abstractive-Timeline-Summarization#7]
Good Morning, 

First of all, thank you for sharing your code related to the abstractive timeline summarization task.

I want to ask you if is possible to access the preprocessing phase to apply the model to new benchmark datasets related to timeline summarization.

Thanks.

**Comment by julmaxi** [comment]
I have added a README with the relevant instructions.
I have not tested the system on new corpora myself, so I am not entirely sure it works.
Let me know if this is helpful.

**Comment by MorenoLaQuatra** [comment]
Thank you for the quick update. At the moment I am not able to reproduce your steps, besides some path-related problem that I solve directly from the code, I have a problem related to the `.tokenized` file parsing. 

Indeed, it seems it looks for an XML file, however, even using the tilse `get-and-preprocess-data` I am only able to get a plain text file. I have the `.timeml` file that corresponds to XML files, is it the correct behavior?

**Comment by MorenoLaQuatra** [comment]
I leave below the trace of the error while using as extension `doc_prefix = ".tokenized"`:

```
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```

This is instead while using `doc_prefix = ".tokenized.timeml"`:

```
Traceback (most recent call last):
  File "save_tl_corpus_entities.py", line 21, in <module>
    corpus = DatedTimelineCorpusReader(args.timeml_prefix, args.timeml_prefix).run(t_path+"/articles/", t_path+"/articles/")
  File "/MYPATH/Abstractive-Timeline-Summarization/tlgraphsum/reader.py", line 695, in run
    sentences = self.reader.read(doc_fname, timeml_fname, dir_date)
  File "/MYPATH/Abstractive-Timeline-Summarization/tlgraphsum/reader.py", line 580, in read
    doc = self.stanford_reader.run(stanford_path)
  File "/MYPATH/Abstractive-Timeline-Summarization/tlgraphsum/reader.py", line 280, in run
    for xml_sent in root.find("document").find("sentences").iter("sentence"):
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by julmaxi** [comment]
Have you parsed the files using Stanford CoreNLP already as in step 3?
This is what the reader is looking for.
Perhaps the ".tokenized" naming is slightly misleading. They are in fact supposed to be CoreNLP XML files parsed from the corresponding tokenized files.

**Comment by MorenoLaQuatra** [comment]
Okey, I think this is what I miss, do I need all annotations from CoreNLP or only some of them (thus, I can sped up computation). 
Annotations actually are: tokenize,ssplit,pos,lemma,ner,parse,depparse,coref. Can I drop something?

**Comment by julmaxi** [comment]
You should be able to leave out coreference, as it is not used by the system.

**Comment by MorenoLaQuatra** [comment]
Thank you for the advice. Actually I reached the point where I created the pickle file for each corpus. At this point I should run the tleval.py file right? I didn't get how to do this, what parameters do I need to specify? I know I need the config file and corpus pickle, however I get the following error:

```
usage: tleval.py [-h] [-f] [-c CONSTRAINT] [-t TIMELINES [TIMELINES ...]]
                 [-m NUM_MULTI_SELECTION_RUNS] [--queryfile QUERYFILE]
                 corpus_pickle config
tleval.py: error: unrecognized arguments: --config --corpus_def
[INFO/MainProcess] process shutting down
[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
[DEBUG/MainProcess] running the remaining "atexit" finalizers
```

The executed command is: `python tleval.py --config ../configs/ap-abstractive-datetr-dateref-clsize-path-depfiltered-greedy-redundancy.json --corpus_def ../preprocessed_data_entities/corpus_name.pkl`

**Comment by julmaxi** [comment]
config and corpus are both positional arguments, so you can't provide them using the optional syntax.
You also need one or more gold timelines, both to evaluate against and as a source for the timeline parameters.

The full call should look something like this, using the command you provided:
`python tlgraphsum/tleval.py -t [PATH_TO_YOUR_GOLD_TIMELINE] -- ../preprocessed_data_entities/corpus_name.pkl ../configs/ap-abstractive-datetr-dateref-clsize-path-depfiltered-greedy-redundancy.json
`

**Comment by MorenoLaQuatra** [comment]
Running the script as you suggest bring to the following error:

```
usage: tleval.py [-h] [-f] [-c CONSTRAINT] [-t TIMELINES [TIMELINES ...]]
                 [-m NUM_MULTI_SELECTION_RUNS] [--queryfile QUERYFILE]
                 corpus_pickle config
tleval.py: error: the following arguments are required: corpus_pickle, config
[INFO/MainProcess] process shutting down
[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
[DEBUG/MainProcess] running the remaining "atexit" finalizers
```

**Comment by MorenoLaQuatra** [comment]
This is the command I run (from tlgraphsum folder):
`python tleval.py -t ../../raw_datasets/data_tl/processed_entities/raw/corpus_name/timelines/tl_0.txt ../preprocessed_data_entities/corpus_name.pkl ../configs/ap-abstractive-datetr-dateref-clsize-path-depfiltered-greedy-redundancy.json`

**Comment by julmaxi** [comment]
You are missing the `--` after the timeline. It is required as you can evaluate on more than one timeline at the same time.

`
python tleval.py -t ../../raw_datasets/data_tl/processed_entities/raw/corpus_name/timelines/tl_0.txt -- ../preprocessed_data_entities/corpus_name.pkl ../configs/ap-abstractive-datetr-dateref-clsize-path-depfiltered-greedy-redundancy.json
`

**Comment by MorenoLaQuatra** [comment]
Sorry, that's my fault, I thought it was a typo. 
Now the error is in looking for the language model. The script does not find the correct model:

`No such file or directory while opening correct_path_to_lm/langmodel20k_vp_3.bin`

I downloaded it from [here](https://www.keithv.com/software/giga/lm_giga_20k_vp_3gram.zip) as you suggest. However, the name is different. Can I safely change the name from this line:

`lm = KenLMLanguageModel.from_file("langmodel20k_vp_3.bin")`

in `graphsum.py`?

**Comment by julmaxi** [comment]
Ah, sorry. I completely forgot I had manually preprocessed the files for the KenLM library to work. I have amended the README. If I remember correctly (sorry, it is some time ago) you need to execute the command
``
bin/build_binary lm_giga_64k_vp_3gram.arpa langmodel20k_vp_3.bin
``
using the tools at https://kheafield.com/code/kenlm/

**Comment by MorenoLaQuatra** [comment]
Thank you. I got it running now. 
I just need to execute the makefile for ap-clustering library before it works as expected.

I had just another little question, is there an already-implemented way to have averaged results over multiple corpora composing the benchmarks (similarly to TL17 or Crisis)?
By the way, for the ROUGE results can I assume the order is the following: concat (P R F), agreement (P R F) and alignment (P R F)?

This is an example of results file:

```
Timeline                Date R  Date P  Date F1 R1 R    R1 P    R1 F1   R2 R    R2 P    R2 F1   R1 R    R1 P    R1 F1   R2 R    R2 P    R2 F1   R1 R    R1 P    R1 F1   R2 R    R2 P    R2 F1
tl_0.txt                0.2667  0.2667  0.2667  0.1883  0.2132  0.2000  0.0392  0.0444  0.0417  0.0390  0.0441  0.0414  0.0216  0.0248  0.0231  0.0393  0.0479  0.0432  0.0216  0.0248  0.0231
All                     0.2667  0.2667  0.2667  0.1883  0.2132  0.2000  0.0392  0.0444  0.0417  0.0390  0.0441  0.0414  0.0216  0.0248  0.0231  0.0393  0.0479  0.0432  0.0216  0.0248  0.0231
```

**Comment by julmaxi** [comment]
You can try the tlanalyse.py file I pushed. It generates a summarizing latex table.
However, it is rather messy and very specific to crisis and TL17, so you might have more luck parsing the result files directly and compute averages yourself.

**Comment by MorenoLaQuatra** [comment]
Ok, thanks. This is what I did, I just ask to be sure if the position of the scores are correct:

```
        date_f1_list.append(float(elements[3]))
        r1_concat_f1_list.append(float(elements[6]))
        r2_concat_f1_list.append(float(elements[9]))
        r1_agreement_f1_list.append(float(elements[12]))
        r2_agreement_f1_list.append(float(elements[15]))
        r1_alignment_f1_list.append(float(elements[18]))
        r2_alignment_f1_list.append(float(elements[21]))
```

considering that `elements[0]` is timeline identifier.

**Comment by julmaxi** [comment]
Yes, that is right. The scores are in the same order as in the paper.
I am going to close this now. Feel free to reopen if you have any further questions.
